From the below output , we see that using df.head() we are getting the first 5 rows of the data

In [1]:
import pandas as pd
df = pd.read_csv('../data/transactions_raw.csv')
df.head()

,transaction_id,timestamp,payment_channel,bank_name,amount,status,failure_reason,hour,day_of_month,month,day_of_week,is_failed,is_night_window,is_salary_window
0,TXN000001,2024-03-03 01:58:20,UPI,ICICI,12320.10,Failed,insufficient_funds,1,3,3,Sunday,1,1,0
1,TXN000002,2024-03-06 16:49:26,Card,Kotak,4438.25,Success,none,16,6,3,Wednesday,0,0,0
2,TXN000003,2024-01-03 21:25:57,UPI,HDFC,25317.23,Failed,network_failure,21,3,1,Wednesday,1,0,0
3,TXN000004,2024-03-10 12:26:47,RTGS,Kotak,21034.04,Success,none,12,10,3,Sunday,0,0,0
4,TXN000005,2024-01-28 00:13:52,Card,SBI,37964.49,Failed,duplicate_txn,0,28,1,Sunday,1,1,1

using df.shape , we are getting the dimensions of the data :
10000 rows and 14 columns

In [2]:
df.shape
print(df.columns)

Index(['transaction_id', 'timestamp', 'payment_channel', 'bank_name', 'amount',
       'status', 'failure_reason', 'hour', 'day_of_month', 'month',
       'day_of_week', 'is_failed', 'is_night_window', 'is_salary_window'],
      dtype='object')

using df.dtypes, we are getting the datatypes of each columns

In [5]:
df.dtypes

transaction_id       object
timestamp            object
payment_channel      object
bank_name            object
amount              float64
status               object
failure_reason       object
hour                  int64
day_of_month          int64
month                 int64
day_of_week          object
is_failed             int64
is_night_window       int64
is_salary_window      int64
dtype: object

using df.isnull(), we are getting the rows that are having null values and using sum we are adding the total number of rows containing zero

In [6]:
df.isnull().sum()

transaction_id      0
timestamp           0
payment_channel     0
bank_name           0
amount              0
status              0
failure_reason      0
hour                0
day_of_month        0
month               0
day_of_week         0
is_failed           0
is_night_window     0
is_salary_window    0
dtype: int64

using df.describe, we are getting the count,mean and standard deviation of the respective columns

In [7]:
df.describe()

,amount,hour,day_of_month,month,is_failed,is_night_window,is_salary_window
count,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,25057.875485,11.464800,15.553600,1.99220,0.233700,0.169100,0.107100
std,14374.447832,6.933006,8.750485,0.82171,0.423205,0.374859,0.309256
min,102.540000,0.000000,1.000000,1.00000,0.000000,0.000000,0.000000
25%,12719.370000,5.000000,8.000000,1.00000,0.000000,0.000000,0.000000
50%,24812.985000,12.000000,15.000000,2.00000,0.000000,0.000000,0.000000
75%,37585.187500,17.000000,23.000000,3.00000,0.000000,0.000000,0.000000
max,49991.080000,23.000000,31.000000,3.00000,1.000000,1.000000,1.000000

using to_datetime we are changing the format of timestamp

In [8]:
df['timestamp'] = pd.to_datetime(df['timestamp'])